# Generated by Django 4.2.11 on 2024-05-10 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211231_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='competences',
            field=models.CharField(default=datetime.datetime(2024, 5, 10, 23, 28, 53, 737866, tzinfo=datetime.timezone.utc), max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='date_de_naissance',
            field=models.CharField(default=datetime.datetime(2024, 5, 10, 23, 29, 3, 840562, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.CharField(default=datetime.datetime(2024, 5, 10, 23, 29, 11, 870296, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sexe',
            field=models.CharField(default=datetime.datetime(2024, 5, 10, 23, 29, 16, 894151, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
    ]
