# Generated by Django 4.2.11 on 2024-05-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_job_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.TextField(default='Bouira, Alger', max_length=100),
        ),
    ]
